### ISSUE TITLE
Default settings when creating new user.

### ISSUE THREAD

**Issue by ThomasAunvik** [ProjectMunchy/Munchy#3]
In default when you try to change your settings, the default language settings are: none. But the text is english.

The same with sex, though i cant be sure if it would be good to have default sex.

Maby also have some default weight and age like, weight: 60kg, and age 30. And maby have a unit behind the weight. So someone does not write as 60000 grams.

**Comment by ProjectMunchy** [comment]
Good idea, working on it right now.

**Comment by ProjectMunchy** [comment]
Feature added. Default user settings now show some default weight and default age.
