### ISSUE TITLE
No recipies are showing after enabling, relaunch, and disabling.

### ISSUE THREAD

**Issue by ThomasAunvik** [ProjectMunchy/Munchy#5]
When selecting all preferences, and saving, the food still shows.

But when you reboot, all the food is gone.

And when you unselect all diabetes, allergies etc, the foods still does not show.

Rebooting the application again after unselecting the things it shows the menus again.

This is also the error after pressing "Show Recipie":
![image](https://user-images.githubusercontent.com/9968151/36634454-19504940-19a5-11e8-9526-245e0502c33d.png)

**Comment by ProjectMunchy** [comment]
Issue fixed. Recipes are now refreshed after setting changes and the error mentioned above is now handled.
